import Menu from '../components/layout/header'
import { Roboto } from "@next/font/google";
import './globals.css'

const roboto = Roboto({
  weight: '400'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <head>
        <title>Next 13</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className='table w-full min-h-screen h-0'>
          <div className="table-cell w-full h-full">
            <div className="flex w-full h-full">
              <Menu />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
